name: rebuild
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # every 1st of each month

jobs:

  update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run container
        uses: ./
        with:
          command: docker compose up --build
          working-directory: $GITHUB_WORKSPACE

      - name: Update repository
        run: ./update-pages.sh